// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ops-redesign/Clean.tsx": () => import("../components/mockups/ops-redesign/Clean.tsx"),
  "./components/mockups/ops-redesign/Layered.tsx": () => import("../components/mockups/ops-redesign/Layered.tsx")
};
